#!/bin/sh

encode() {
    # urlencode <string>

    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:$i:1}"
        case $c in
            [\[\]]) printf '\\%s' "$c" ;;
            *) printf '%s' "$c" ;;
        esac
    done

    LC_COLLATE=$old_lc_collate
}

encode $*
